pinger:
  image: iseif-code:latest
  # command: ls
  command: python app/pinger.py --app_host="server" --redis_host="redis"
  volumes:
   - .:/usr/src/
  links:
   - redis
   - server
server:
  image: iseif-code:latest
  command: python app/app.py --redis_host="redis" --filepath="/data/logs/"
  volumes:
   - .:/usr/src/
   - /data
  links:
   - redis
  ports:
   - "8000"
redis:
  image: redis
  expose:
   - "6379"
